### ISSUE TITLE
Code Refactoring

### ISSUE THREAD

**Issue by pijusch** [piyush96chawla/SentimentAnalysis#6]

**Comment by pijusch** [comment]
Make a util.py file with preprocessing functions. (Since everyone is using same code)

**Comment by lpatel16** [comment]
Util.py created. @snayak04 and @everest146 will need to update their files and basically mirror my new mlp.py (remove preprocessing code, import util.py, append util.* before every function call)

**Comment by pijusch** [comment]
Please close this issue if the files have been created
